# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfx < Formula
  desc "TFx is a standalone CLI tool for HCP Terraform and Terraform Enterprise."
  homepage "https://tfx.rocks/"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/straubt1/tfx/releases/download/v0.4.1/tfx_Darwin_x86_64.tar.gz"
      sha256 "ddb26730dc4c482adcede86b09580e2e3352f884c858b0a2899f5442901b6ae1"

      define_method(:install) do
        bin.install "tfx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/straubt1/tfx/releases/download/v0.4.1/tfx_Darwin_arm64.tar.gz"
      sha256 "8c4abb5625345d9ca65abb85ac9f00970b85162329cc082039ee0dc685c8c078"

      define_method(:install) do
        bin.install "tfx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/straubt1/tfx/releases/download/v0.4.1/tfx_Linux_x86_64.tar.gz"
      sha256 "a8365c13f28cc05abfb7536cfbc41ef4d5dbc62ef2b712b437c132a8252eb883"
      define_method(:install) do
        bin.install "tfx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/straubt1/tfx/releases/download/v0.4.1/tfx_Linux_arm64.tar.gz"
      sha256 "029d81a461e72da44f46f1b20f9e031b6eb8a5e0ca54f6198128aa76a4cdb0bb"
      define_method(:install) do
        bin.install "tfx"
      end
    end
  end
end
